apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: $#REY07
  MYSQL_USER: root
  MYSQL_DB_URL: mysql+pymysql://root:$#REY07@mysql-service:3306/social_media